name: agenda
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.7
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^5.0.0
  toast: ^8.0.7

flutter:
  uses-material-design: true

gem:
activesupport: ^7.0.8